apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: nginx-server
  namespace: krateo-system
spec:
  chart:
    url: oci://ghcr.io/leovice-org/nginx-cd-200/nginx-server
    version: "0.1.0"
